"""add collaborative models

Revision ID: 2f0e7c1e9d15
Revises: 010
Create Date: 2026-02-16 13:51:03.047301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f0e7c1e9d15'
down_revision: Union[str, None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('nombre_original', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.BIGINT(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archivos_entidad', 'archivos', ['entidad_tipo', 'entidad_id'], unique=False)
    op.create_index(op.f('ix_archivos_id'), 'archivos', ['id'], unique=False)
    op.create_index(op.f('ix_archivos_usuario_id'), 'archivos', ['usuario_id'], unique=False)
    op.create_table('fichas_conocimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ficha', sa.String(length=50), nullable=False),
    sa.Column('contenido_md', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fichas_conocimiento', 'fichas_conocimiento', ['entidad_tipo', 'entidad_id', 'tipo_ficha', 'estado'], unique=False)
    op.create_index(op.f('ix_fichas_conocimiento_id'), 'fichas_conocimiento', ['id'], unique=False)
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('visibilidad', sa.String(length=50), nullable=False),
    sa.Column('slug_publico', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug_publico')
    )
    op.create_index('idx_listas_usuario_visibilidad', 'listas', ['usuario_id', 'visibilidad'], unique=False)
    op.create_index(op.f('ix_listas_id'), 'listas', ['id'], unique=False)
    op.create_index(op.f('ix_listas_usuario_id'), 'listas', ['usuario_id'], unique=False)
    op.create_table('lugares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nombre', name='uq_lugar_usuario_nombre')
    )
    op.create_index(op.f('ix_lugares_id'), 'lugares', ['id'], unique=False)
    op.create_index(op.f('ix_lugares_usuario_id'), 'lugares', ['usuario_id'], unique=False)
    op.create_table('listas_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('variedad_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_ofrecida', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('(lote_id IS NOT NULL OR variedad_id IS NOT NULL)', name='chk_lista_item_lote_o_variedad'),
    sa.ForeignKeyConstraint(['lista_id'], ['listas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_semillas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variedad_id'], ['variedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listas_items_id'), 'listas_items', ['id'], unique=False)
    op.create_index(op.f('ix_listas_items_lista_id'), 'listas_items', ['lista_id'], unique=False)
    op.create_index(op.f('ix_listas_items_lote_id'), 'listas_items', ['lote_id'], unique=False)
    op.create_index(op.f('ix_listas_items_variedad_id'), 'listas_items', ['variedad_id'], unique=False)
    op.alter_column('square_foot_gardening', 'plantas_original',
               existing_type=sa.INTEGER(),
               comment='Plantas por cuadrado - Método original SFG',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'plantas_multisow',
               existing_type=sa.INTEGER(),
               comment='Plantas por cuadrado - Siembra múltiple',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'plantas_macizo',
               existing_type=sa.INTEGER(),
               comment='Plantas por cuadrado - Siembra en macizo',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'espaciado_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Espaciado entre plantas en cm',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('square_foot_gardening', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('square_foot_gardening_especie_id_key', 'square_foot_gardening', type_='unique')
    op.drop_index('ix_square_foot_gardening_especie_id', table_name='square_foot_gardening')
    op.create_index(op.f('ix_square_foot_gardening_especie_id'), 'square_foot_gardening', ['especie_id'], unique=True)
    op.create_index(op.f('ix_square_foot_gardening_id'), 'square_foot_gardening', ['id'], unique=False)
    op.add_column('temporadas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('temporadas', sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
    op.add_column('temporadas', sa.Column('fecha_fin', sa.DateTime(), nullable=True))
    op.alter_column('temporadas', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_temporadas_usuario_id'), 'temporadas', ['usuario_id'], unique=False)
    op.create_unique_constraint('uq_temporada_usuario_nombre', 'temporadas', ['usuario_id', 'nombre'])
    op.create_foreign_key(None, 'temporadas', 'users', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_column('temporadas', 'clima_esperado')
    op.drop_column('temporadas', 'mes_fin')
    op.drop_column('temporadas', 'mes_inicio')
    op.drop_column('temporadas', 'descripcion')
    op.drop_column('temporadas', 'anno')
    op.drop_column('temporadas', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporadas', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('temporadas', sa.Column('anno', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('temporadas', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('temporadas', sa.Column('mes_inicio', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('temporadas', sa.Column('mes_fin', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('temporadas', sa.Column('clima_esperado', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'temporadas', type_='foreignkey')
    op.drop_constraint('uq_temporada_usuario_nombre', 'temporadas', type_='unique')
    op.drop_index(op.f('ix_temporadas_usuario_id'), table_name='temporadas')
    op.alter_column('temporadas', 'nombre',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('temporadas', 'fecha_fin')
    op.drop_column('temporadas', 'fecha_inicio')
    op.drop_column('temporadas', 'usuario_id')
    op.drop_index(op.f('ix_square_foot_gardening_id'), table_name='square_foot_gardening')
    op.drop_index(op.f('ix_square_foot_gardening_especie_id'), table_name='square_foot_gardening')
    op.create_index('ix_square_foot_gardening_especie_id', 'square_foot_gardening', ['especie_id'], unique=False)
    op.create_unique_constraint('square_foot_gardening_especie_id_key', 'square_foot_gardening', ['especie_id'])
    op.alter_column('square_foot_gardening', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('square_foot_gardening', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('square_foot_gardening', 'espaciado_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Espaciado entre plantas en cm',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'plantas_macizo',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Plantas por cuadrado - Siembra en macizo',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'plantas_multisow',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Plantas por cuadrado - Siembra múltiple',
               existing_nullable=True)
    op.alter_column('square_foot_gardening', 'plantas_original',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Plantas por cuadrado - Método original SFG',
               existing_nullable=True)
    op.drop_index(op.f('ix_listas_items_variedad_id'), table_name='listas_items')
    op.drop_index(op.f('ix_listas_items_lote_id'), table_name='listas_items')
    op.drop_index(op.f('ix_listas_items_lista_id'), table_name='listas_items')
    op.drop_index(op.f('ix_listas_items_id'), table_name='listas_items')
    op.drop_table('listas_items')
    op.drop_index(op.f('ix_lugares_usuario_id'), table_name='lugares')
    op.drop_index(op.f('ix_lugares_id'), table_name='lugares')
    op.drop_table('lugares')
    op.drop_index(op.f('ix_listas_usuario_id'), table_name='listas')
    op.drop_index(op.f('ix_listas_id'), table_name='listas')
    op.drop_index('idx_listas_usuario_visibilidad', table_name='listas')
    op.drop_table('listas')
    op.drop_index(op.f('ix_fichas_conocimiento_id'), table_name='fichas_conocimiento')
    op.drop_index('idx_fichas_conocimiento', table_name='fichas_conocimiento')
    op.drop_table('fichas_conocimiento')
    op.drop_index(op.f('ix_archivos_usuario_id'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_id'), table_name='archivos')
    op.drop_index('idx_archivos_entidad', table_name='archivos')
    op.drop_table('archivos')
    # ### end Alembic commands ###
